name: crossroad
description: Simple router without dependencies for shelf.
version: 0.0.1-alpha.1
homepage: https://github.com/reimashi/crossroad
author: Aitor González Fernández <reimashi@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  shelf: ^0.7.0

dev_dependencies:
  test: ^0.12.0
